language: r
sudo: false
cache: packages

os:
- linux
- osx

r:
- release
- oldrel
- devel

matrix:
  exclude:
  - os: osx
    r: devel

notifications:
  email:
    - thomas@roh.engineering.com
