---
title: "Fitting Distributions"
author: "Thomas Roh"
date: "February 13, 2017"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fitting Distributions}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 5, fig.width = 7)
library(fitur)
library(ggplot2)
```

## Motivation

## Summary Statistics

kurtosis - shape of the distibutions tails, skewedness
moments
histogram

```{r stats}
set.seed(438)
x <- rweibull(10000, 5)
sumStats <- summarize_stats(x)
```

### Histogram

```{r histPlot}
dt <- data.frame(x)
nbins <- 30
g <- ggplot(dt, aes(x)) +
  geom_histogram(aes(y = ..density..), 
                bins = nbins, fill = NA, color = "black") +
  theme_bw() +
  theme(panel.grid = element_blank())
g
```


## Diagnostic Plots

### Histogram vs Density Plot

```{r densPlot}
dists <- c('gamma', 'lnorm', 'weibull')
cols <- c('red', 'blue', 'yellow')
multipleFits <- lapply(dists, fit_univariate, x = x)
for (i in 1:length(multipleFits)) {
  g <- g +
    stat_function(fun = multipleFits[[i]][[1]],
                  aes_(color = dists[i]),
                  size = 1)
}
g +
  scale_color_manual(name = "distribution",
                     values = cols, 
                     breaks = paste0('d', dists))
```

### Q-Q Plot

```{r qqplot}
plot_qq(x, multipleFits)
```

### P-P Plot

```{r ppplot}
probs <- 1:length(x)/(length(x) + 1)
theorPerc <- lapply(multipleFits, function(fit) {
  data.frame(distribution = names(fit)[2],
             theoretical = sort(fit[[2]](sort(x))),
             stringsAsFactors = FALSE)
})
theorPerc <- do.call('rbind.data.frame', theorPerc)
pp <- data.frame(sample = rep(probs, 3), 
                 theorPerc)

ggplot(pp) +
  geom_point(aes(x = theoretical, y = sample, color = distribution)) +
  geom_abline(slope = 1,
              color = 'black') +
  scale_color_manual(values = c('blue', 'red', 'yellow')) +
  theme_bw() +
  theme(panel.grid = element_blank())
```


## Goodness of Fit

ks test
